% =========================================================================
% batch_process_single_patient_ACAI_integrated.m
%
% This script processes a single patient for ACAI analysis.
% 1. It initializes SPM and ACAI paths.
% 2. It runs CAT12 segmentation on the T1 image using specific parameters.
% 3. It verifies the output files (p1, y, iy) and the coregistered PET.
% 4. It executes the ACAI calculation.
%
% !!!! IT ASSUMES MNI VOXEL DIMENSIONS ARE 1 x 1 x 1
% =========================================================================

clear; clc;

% --- 0. CONFIGURATION ---
% Full path to the original T1 NIfTI file.
t1_image_file = 'E:\studie_lieselotte\Clean_dir\20\sub-020_acq-1_3DT1w.nii';

% Full path to the FDG-PET NIfTI file (must be coregistered to the T1)
pet_image_file = 'E:\studie_lieselotte\Clean_dir\20\coreg_to_T1\sub-020_acq-1_desc-LMduetto_pet_toT1_affine_sm45.nii';

% Paths to required toolboxes and scripts
% Ensure this points to the SPM12 folder containing the 'tpm' and 'toolbox/cat12' subfolders
% for example C:\MATLAB\R2023b\toolbox\spm12
spm_path = 'C:\MATLAB\R2023b\toolbox\spm12'; 

% Path to the directory containing 'LCN12_calc_ACAI_GACAI_preprocessed.m'
% eg the directory of this script
acai_script_path = 'C:\Users\jgijs0\OneDrive - KU Leuven (1)\lopende studies\ACAI study\github_script\cat12_ACAI';

% ACAI Kernel settings
kernel_type = 'Gaussian'; % 'Gaussian', 'Cubic', 'Sphere'
kernel_size = 9;          % FWHM for Gaussian, side for Cubic, diameter for Sphere

% -----------------------------

% --- 1. Setup Environment ---
fprintf('--- 1. Setting up Environment ---\n');
try
    addpath(spm_path);
    addpath(acai_script_path);
    
    spm_jobman('initcfg');
    spm('defaults', 'PET');
    fprintf('  SPM and script paths added.\n');
catch ME
    fprintf('  ERROR: Could not initialize SPM or add paths.\n');
    fprintf('  Please check your `spm_path` and `acai_script_path` variables.\n');
    rethrow(ME);
end

% --- 2. Run CAT12 Segmentation ---
fprintf('\n--- 2. Running CAT12 Segmentation ---\n');
% We check if the CAT12 toolbox is accessible
if isempty(which('cat12'))
    error('CAT12 toolbox not found. Please ensure CAT12 is installed in spm12/toolbox/cat12.');
end

try
    % Generate the batch structure using the local function defined below
    matlabbatch = cat12_ACAI_batch(t1_image_file);
    
    fprintf('  CAT12 batch job created. Starting segmentation (this may take time)...\n');
    spm_jobman('run', matlabbatch);
    fprintf('  CAT12 Segmentation complete.\n');
    
catch ME
    fprintf('  ERROR: CAT12 Segmentation failed.\n');
    rethrow(ME);
end

% --- 3. Define CAT12 Output File Paths ---
fprintf('\n--- 3. Defining CAT12 Output Paths ---\n');
% CAT12 places outputs in an 'mri' subdirectory in the T1's folder by default (based on the batch settings)
[t1_path, t1_name, t1_ext] = spm_fileparts(t1_image_file);
cat12_mri_path = fullfile(t1_path, 'mri');

% Define paths for the files generated by CAT12 needed by ACAI
gm_image_native = fullfile(cat12_mri_path, ['p1' t1_name t1_ext]);
deformationfield_forward = fullfile(cat12_mri_path, ['y_' t1_name t1_ext]);
deformationfield_inverse = fullfile(cat12_mri_path, ['iy_' t1_name t1_ext]);
target_GMactivityimage_native = ''; 

fprintf('  Base T1: %s\n', t1_image_file);
fprintf('  Looking in CAT12 ''mri'' folder: %s\n', cat12_mri_path);

% --- 4. Verify All Required Files Exist ---
fprintf('\n--- 4. Verifying All Files for ACAI ---\n');
files_ok = true;

if ~exist(pet_image_file, 'file')
    fprintf('  ERROR: Coregistered PET file not found: %s\n', pet_image_file);
    files_ok = false;
end

if ~exist(gm_image_native, 'file')
    fprintf('  ERROR: CAT12 GM (p1) file not found: %s\n', gm_image_native);
    files_ok = false;
end

if ~exist(deformationfield_forward, 'file')
    fprintf('  ERROR: CAT12 Forward deformation (y_) not found: %s\n', deformationfield_forward);
    files_ok = false;
end

if ~exist(deformationfield_inverse, 'file')
    fprintf('  ERROR: CAT12 Inverse deformation (iy_) not found: %s\n', deformationfield_inverse);
    files_ok = false;
end

if ~files_ok
    fprintf('  --> STOPPING processing due to missing files.\n');
    return;
end

fprintf('  Found All Required Files:\n');
fprintf('    - PET: %s\n', pet_image_file);
fprintf('    - GM (p1): %s\n', gm_image_native);
fprintf('    - Def. Fwd (y_): %s\n', deformationfield_forward);
fprintf('    - Def. Inv (iy_): %s\n', deformationfield_inverse);

% --- 5. Call the ACAI calculation function ---
fprintf('\n--- 5. Calling LCN12_calc_ACAI_GACAI_preprocessed ---\n');
try
    LCN12_calc_ACAI_GACAI_preprocessed(pet_image_file, gm_image_native, ...
        deformationfield_forward, deformationfield_inverse, kernel_type, kernel_size, ...
        target_GMactivityimage_native);
        
    fprintf('  --> SUCCESS: ACAI processing complete.\n');
catch ME
    fprintf('  --> ERROR during ACAI calculation: %s\n', ME.message);
    for k=1:length(ME.stack)
        fprintf('      In %s at line %d\n', ME.stack(k).name, ME.stack(k).line);
    end
end

fprintf('\n--------------------------------------------------\n');
fprintf('Batch processing complete for this patient.\n');